# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

name: Flutter MVVM Project Release APK
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
- uses: subosito/flutter-action@v1  
    - uses: actions/subosito/flutter-action@v1
      with:
        flutter-version:  '2.5.3'
    - run: flutter pub get
    - run: flutter build apk --release
    - name: Release Apk
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/app-release.apk"
        token: ${{secrets.GITHUBACTIONTOKEN}}
